# Generated by Django 6.0.6 on 2026-07-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_percent',
            new_name='discount',
        ),
    ]
