# Generated by Django 6.0.6 on 2026-06-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_description_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
