# Generated by Django 6.0.6 on 2026-06-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='OrderItem',
        ),
    ]
